[workspace]
package.version = "0.1.0"
package.edition = "2021"

[package]
name = "symmetric_executor"
edition.workspace = true
version.workspace = true

[dependencies]
futures = "0.3.31"
libc = "0.2.167"
wit-bindgen = { version = "0.36.0", path = "../guest-rust" }
wit-bindgen-rt = { version = "0.36.0", path = "../guest-rust/rt" }

[lib]
crate-type = ["cdylib"]

[features]
# always off feature
never = []
# output debugging information
trace = []
